homeassistant:
  # Name of the location where Home Assistant is running
  name: Bya
  # Location required to calculate the time the sun rises and sets
  latitude: 59.2897
  longitude: 15.1825
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 38
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm 

  customize: !include customize.yaml

script: !include_dir_named scripts
automation: !include_dir_merge_list automation/
zone: !include zones.yaml
sensor: !include sensors.yaml
device_tracker: !include device_tracker.yaml


tellduslive:
  public_key: !secret public_key
  private_key: !secret private_key
  token: !secret token
  token_secret: !secret token_secret
  update_interval:
    seconds: 15

recorder:
  purge_days: 15
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun   # Don't record sun data
      - sensor.last_boot
      - sensor.date

google:
  client_id: !secret client_id
  client_secret: !secret client_secret
  track_new_calendar: true

config:

input_select:
  radio_station:
    name: Radio Station
    options:
      - Bandit Rock
      - Rix FM
      - P3
      - Senaste Ekot
      - None
    initial: None
    icon: mdi:radio
  radio_player:
    name: Radio Player
    options:
      - Gym
      - Sovrum
      - None
    initial: None
    icon: mdi:airplay

media_player:
  - platform: denonavr
    host: 192.168.1.21
    name: Gymmet
  - platform: apple_tv
    host: 192.168.1.22
    login_id: !secret login_id
    name: Apple TVardagsrum
  - platform: cast
    host: 192.168.1.25
    name: Pappas sovrum
http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
#updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google
  language: sv
